let DATA=null, chartPoints=[], map=null;
const money=v=>'$'+Number(v).toLocaleString('en-US',{maximumFractionDigits:0});
const fmtInt=v=>Number(v).toLocaleString('en-US');
const pct=v=>(Number(v)>=0?'+':'')+Number(v).toFixed(1)+'%';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function set(id,v){const el=document.getElementById(id);if(el)el.textContent=v}
function startClock(){const tick=()=>set('clockUtc',new Date().toLocaleString('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})+' UTC');tick();setInterval(tick,1000)}
async function load(){try{const r=await fetch('data.json?ts='+Date.now());if(!r.ok)throw new Error('HTTP '+r.status);DATA=await r.json();render()}catch(e){set('updateState','data file unavailable')}}
function render(){const ix=DATA.index,c=DATA.corridor,t=DATA.transit,ca=DATA.caspian,cap=DATA.capacity||{};
  set('mciIndex',Number(ix.current_index).toFixed(1));set('basePeriod',ix.base_period.toUpperCase());set('coverage',ix.coverage);set('mciPrice',money(ix.current_usd_feu));set('fixingPeriod',ix.current_period);set('mciDelta',`${pct(ix.change_since_base_pct)} VS BASE`);
  set('teuYtd',fmtInt(c.teu_ytd)+' TEU');set('teuPeriod',c.period);set('teuYoy',pct(c.yoy_pct));set('blockTrains',fmtInt(c.block_trains));set('trainGrowth',pct(c.block_trains_yoy_pct)+' YoY');set('transitDays',t.reference_days+' days');set('transitRoute',t.route);
  set('westShare',c.westbound_share_pct.toFixed(1)+'%');set('westTeu',fmtInt(c.westbound_teu)+' TEU');set('eastTeu',fmtInt(c.eastbound_teu)+' TEU');document.getElementById('westBar').style.width=c.westbound_share_pct+'%';document.getElementById('eastBar').style.width=(100-c.westbound_share_pct)+'%';
  set('caspianTeu',fmtInt(ca.aktau_alat_teu)+' TEU');set('caspianPeriod',ca.latest_month);set('caspianYoy','+'+ca.yoy_pct+'%');set('distance',fmtInt(t.distance_km)+' km');set('ferryLoad',(ca.ferry_load_pct||80)+'%');
  set('capacityMt',(cap.designed_mt||6).toFixed(1));set('cargoMt',(cap.ytd_mt||3).toFixed(1)+'m t');set('cargoPeriod',cap.period||'Jan–Aug 2026');set('cargoYoy',pct(cap.yoy_pct||22));
  const ocean=(DATA.transport_prices||[]).find(x=>x.code==='OCEAN-EU'); if(ocean){const op=100*(ix.current_usd_feu/ocean.mid-1);set('oceanPremium',pct(op))}
  const dt=new Date(DATA.meta.generated_at);const stamp=isNaN(dt)?DATA.meta.generated_at:dt.toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});set('lastUpdated',stamp);set('footerUpdated','Source check '+stamp);const u=DATA.meta.update_results;set('updateState',u?Object.entries(u).map(([k,v])=>`${k}: ${v===true?'updated':v===false?'no change':v}`).join(' · '):'verified snapshot');
  document.getElementById('componentStrip').innerHTML=ix.components.map(x=>`<div class="ref"><div class="top"><span>${esc(x.code)} · ${(x.weight*100).toFixed(0)}%</span><span>${esc(x.period)}</span></div><strong>${money(x.mid)} / FEU</strong><small>${esc(x.lane)}</small></div>`).join('');
  document.getElementById('laneRows').innerHTML=ix.components.map(x=>`<tr><td><strong>${esc(x.code)}</strong></td><td>${esc(x.lane)}</td><td>${(x.weight*100).toFixed(0)}%</td><td>${money(x.low)}–${money(x.high)}</td><td><strong>${money(x.mid)}</strong></td><td>${esc(x.period)}</td></tr>`).join('');
  renderPricing();renderLog();renderNews();renderSources();drawIndex();initMap();
}
function renderPricing(){const rows=DATA.transport_prices||[];document.getElementById('priceGrid').innerHTML=rows.map(r=>`<article class="price-card"><div class="mode"><span>${esc(r.mode)}</span><span>${esc(r.period)}</span></div><strong>${esc(r.display)}</strong><div class="unit">${esc(r.unit)}</div><p>${esc(r.lane)} · ${esc(r.transit||'')}<br><a href="${esc(r.source_url)}" target="_blank" rel="noreferrer">${esc(r.source)} ↗</a></p></article>`).join('')}
function renderLog(){if(!DATA)return;const q=(document.getElementById('searchBox').value||'').toLowerCase(),ty=document.getElementById('typeFilter').value;const rows=DATA.log.filter(r=>(ty==='all'||r.type===ty)&&Object.values(r).join(' ').toLowerCase().includes(q));document.getElementById('logRows').innerHTML=rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.type)}</td><td>${esc(r.lane)}</td><td><strong>${esc(r.value)}</strong></td><td>${esc(r.source)}</td></tr>`).join('')||'<tr><td colspan="5">No matching records.</td></tr>'}
function renderNews(){const news=DATA.news||[];document.getElementById('newsGrid').innerHTML=news.map(n=>`<a class="news-card" href="${esc(n.url)}" target="_blank" rel="noreferrer"><div class="meta"><span>${esc(n.source)}</span><span>${esc(n.date)}</span></div><h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p><div class="arrow">READ SOURCE ↗</div></a>`).join('')}
function renderSources(){const urls=new Map();[...(DATA.index.components||[]),DATA.corridor,DATA.transit,DATA.caspian,DATA.capacity,...(DATA.transport_prices||[])].filter(Boolean).forEach(x=>{if(x.source_url)urls.set(x.source_url,x.source||x.code||'Source')});document.getElementById('sourceLinks').innerHTML=[...urls].map(([u,n])=>`<a href="${esc(u)}" target="_blank" rel="noreferrer">${esc(n)} ↗</a>`).join('')}
function drawIndex(){const c=document.getElementById('indexChart');if(!c||!DATA)return;const xs=DATA.index.history,dpr=devicePixelRatio||1,W=c.clientWidth||900,H=220;c.width=W*dpr;c.height=H*dpr;c.style.height=H+'px';const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,W,H);const p={l:48,r:18,t:24,b:34};let vals=xs.map(d=>d.index),lo=Math.min(...vals),hi=Math.max(...vals);lo=Math.floor((lo-5)/5)*5;hi=Math.ceil((hi+5)/5)*5;if(lo===hi){lo-=5;hi+=5}x.font='9px DM Mono';x.fillStyle='#65706c';x.strokeStyle='#202524';x.lineWidth=1;for(let i=0;i<5;i++){const v=hi-(hi-lo)*i/4,y=p.t+(H-p.t-p.b)*i/4;x.beginPath();x.moveTo(p.l,y);x.lineTo(W-p.r,y);x.stroke();x.fillText(v.toFixed(0),6,y+3)}const px=i=>p.l+(W-p.l-p.r)*(xs.length===1?.5:i/(xs.length-1)),py=v=>p.t+(hi-v)/(hi-lo)*(H-p.t-p.b);x.strokeStyle='#37e38d';x.lineWidth=2;x.beginPath();xs.forEach((d,i)=>{const X=px(i),Y=py(d.index);i?x.lineTo(X,Y):x.moveTo(X,Y)});x.stroke();chartPoints=[];xs.forEach((d,i)=>{const X=px(i),Y=py(d.index);chartPoints.push({x:X,y:Y,d});x.fillStyle='#080909';x.strokeStyle='#37e38d';x.lineWidth=2;x.beginPath();x.arc(X,Y,5,0,Math.PI*2);x.fill();x.stroke();x.fillStyle='#7c8783';x.textAlign='center';x.fillText(d.period,X,H-10)});x.textAlign='left'}
function chartNearest(ev){const c=document.getElementById('indexChart'),r=c.getBoundingClientRect(),mx=ev.clientX-r.left,my=ev.clientY-r.top;let hit=null,dist=Infinity;chartPoints.forEach(p=>{const d=Math.hypot(mx-p.x,my-p.y);if(d<dist){dist=d;hit=p}});return dist<28?hit:null}
function showChartTip(ev,commit=false){const h=chartNearest(ev),tip=document.getElementById('chartTooltip'),card=document.getElementById('chartCard');if(!h){tip.hidden=true;return}const r=card.getBoundingClientRect();tip.hidden=false;tip.style.left=(ev.clientX-r.left+12)+'px';tip.style.top=(ev.clientY-r.top-10)+'px';tip.innerHTML=`<b>${esc(h.d.period)}</b><br>MCI ${Number(h.d.index).toFixed(1)} · ${money(h.d.usd_feu)}/FEU`;if(commit)set('fixingDetail',`${h.d.period} — MCI ${Number(h.d.index).toFixed(1)} · ${money(h.d.usd_feu)}/FEU · ${h.d.coverage||''}`)}
function initMap(){if(map||!window.L)return;const nodes=DATA.route_nodes||[];map=L.map('routeMap',{zoomControl:true,scrollWheelZoom:true}).setView([43.5,64],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:8,attribution:'© OpenStreetMap'}).addTo(map);const byId=Object.fromEntries(nodes.map(n=>[n.id,n]));const line=(ids,color,dash)=>L.polyline(ids.map(id=>[byId[id].lat,byId[id].lon]),{color,weight:3,opacity:.88,dashArray:dash||null}).addTo(map);
  line(['xian','khorgos','altynkol','aktau'],'#37e38d');line(['aktau','alat'],'#55c2ff','8 8');line(['alat','tbilisi'],'#37e38d');line(['tbilisi','kars','istanbul'],'#f5b94c');line(['tbilisi','poti'],'#f5b94c');line(['poti','constanta'],'#55c2ff','8 8');
  nodes.forEach(n=>{const cls=n.mode==='Port'?'port':n.branch?'branch':'';const icon=L.divIcon({className:'',html:`<div class="mci-marker ${cls}"></div>`,iconSize:[14,14],iconAnchor:[7,7]});const m=L.marker([n.lat,n.lon],{icon}).addTo(map);m.bindTooltip(n.name,{direction:'top'});m.on('click',()=>showNode(n))});map.fitBounds(nodes.map(n=>[n.lat,n.lon]),{padding:[30,30]})}
function showNode(n){document.getElementById('mapPanel').innerHTML=`<span>${esc(n.kind||'CORRIDOR NODE')}</span><strong>${esc(n.name)}</strong><p>${esc(n.description)}</p><dl><dt>Country</dt><dd>${esc(n.country)}</dd><dt>Mode</dt><dd>${esc(n.mode)}</dd><dt>Role</dt><dd>${esc(n.role)}</dd></dl>`}
['searchBox','typeFilter'].forEach(id=>document.getElementById(id).addEventListener('input',renderLog));const cc=document.getElementById('chartCard');cc.addEventListener('mousemove',e=>showChartTip(e,false));cc.addEventListener('mouseleave',()=>document.getElementById('chartTooltip').hidden=true);cc.addEventListener('click',e=>showChartTip(e,true));window.addEventListener('resize',()=>{clearTimeout(window.__rz);window.__rz=setTimeout(drawIndex,120)});startClock();load();
