const $=id=>document.getElementById(id); const money=n=>n==null?'—':`$${Number(n).toLocaleString('en-US',{maximumFractionDigits:0})}`; const num=n=>n==null?'—':Number(n).toLocaleString('en-US');
let DATA=null;
function set(id,v){const e=$(id);if(e)e.textContent=v}
function render(d){DATA=d; const m=d.mci,c=d.corridor,a=d.aktau,o=d.ocean,ais=d.ais||{};
 set('mciIndex',m.index.toFixed(1));set('aboutMciIndex',m.index.toFixed(1));set('mciPrice',money(m.current_basket_usd));set('aboutMciPrice',money(m.current_basket_usd));set('aboutBasketPrice',money(m.current_basket_usd)+' / FEU');set('basePeriod',m.base_period.toUpperCase());set('baseBasketUsd',money(m.base_basket_usd));set('coverage',d.meta.coverage);set('fixingPeriod',d.meta.fixing_period);set('laneCount',m.lanes.length);set('mciDelta',`+${(m.index-100).toFixed(1)}% vs base`);
 const prem=((m.current_basket_usd/o.shanghai_rotterdam_40ft)-1)*100;set('heroOceanPremium',`+${prem.toFixed(0)}%`);set('oceanPremium',`+${prem.toFixed(0)}%`);set('lastUpdated',new Date(d.meta.published_at).toLocaleString());set('footerUpdated',new Date(d.meta.published_at).toISOString().replace('T',' ').slice(0,16)+' UTC');set('updateState','data loaded');
 $('componentStrip').innerHTML=m.lanes.map(x=>`<div><span>${x.code} · ${Math.round(x.weight*100)}%</span><b>${money(x.midpoint)}</b><small>${x.lane}</small></div>`).join('');
 set('aktauCapacity',a.capacity_mt);set('aktauBerths',a.berths);set('aktauNav',a.navigation);set('aktauOps',a.operations);set('aktauOpenStorage',num(a.open_storage_m2)+' m²');set('hubStage1',num(a.hub_stage1_teu));set('hubDesign',num(a.hub_design_teu));set('hubStatus',a.hub_status);set('aktauCapex',`KZT ${a.capex_kzt_bn}bn`);$('hubCapacityFill').style.width=Math.min(100,(a.hub_stage1_teu/a.hub_design_teu)*100)+'%';
 set('aktauAlatTeu',num(a.aktau_alat_teu)+' TEU');set('aktauAlatPeriod',a.aktau_alat_period);set('aktauAlatYoy',`+${a.aktau_alat_yoy_pct.toFixed(1)}%`);set('aktauFerryLoad',a.ferry_load_constraint);set('aktauDraft',a.draft_target);set('aktauDredging',a.dredging);set('aktauTariffDate',a.tariff_date);
 $('pressureFactors').innerHTML=`<div><span>AIS activity feed</span><b>${ais.status==='live'?'LIVE':'PENDING'}</b></div><div><span>Dredging / draft</span><b>${a.draft_target}</b></div><div><span>Ferry usable load</span><b>${a.ferry_load_constraint}</b></div>`;
 set('aisStatus',ais.status==='live'?'LIVE FEED':ais.status==='stale'?'LAST VALID SNAPSHOT':'API NOT CONFIGURED');set('aisUpdated',ais.updated_at?new Date(ais.updated_at).toLocaleString():'Set VesselFinder API secret');set('aisVessels',num(ais.vessels_in_area));set('aisStopped',num(ais.stopped_or_anchored));set('aisArrivals24',num(ais.arrivals_24h));set('aisDepartures24',num(ais.departures_24h));set('aisArrivals7d',num(ais.arrivals_7d));set('aisDepartures7d',num(ais.departures_7d));
 const mix=ais.vessel_mix||{};$('aisMix').innerHTML=Object.keys(mix).length?Object.entries(mix).sort((x,y)=>y[1]-x[1]).map(([k,v])=>`<span class="ais-chip">${k.toUpperCase()} · ${v}</span>`).join(''):'<span class="ais-chip">Feed awaiting configuration</span>';
 set('teuYtd',num(c.teu_ytd));set('teuPeriod',c.teu_period);set('teuYoy',`+${c.teu_yoy_pct}%`);set('blockTrains',num(c.block_trains));set('trainGrowth',`+${c.block_trains_yoy_pct}% YoY`);set('transitDays',c.transit_days+' d');set('transitRoute',c.transit_route);set('capacityMt',c.designed_capacity_mt);set('cargoMt','>'+c.cargo_mt);set('cargoPeriod',c.cargo_period);set('cargoYoy',`+${c.cargo_yoy_pct}%`);
 const total=c.westbound_teu+c.eastbound_teu,share=c.westbound_teu/total*100;set('westShare',share.toFixed(0)+'%');set('westTeu',num(c.westbound_teu)+' TEU');set('eastTeu',num(c.eastbound_teu)+' TEU');$('westBar').style.width=share+'%';$('eastBar').style.width=(100-share)+'%';
 $('laneRows').innerHTML=m.lanes.map(x=>`<tr><td>${x.code}</td><td>${x.lane}</td><td>${Math.round(x.weight*100)}%</td><td>${money(x.low)}–${money(x.high)}</td><td>${money(x.midpoint)}</td><td>${x.period}</td></tr>`).join('');
 $('priceGrid').innerHTML=m.lanes.map(x=>`<article class="price-card"><span>${x.code} · ${x.lane}</span><strong>${money(x.midpoint)}</strong><small>${money(x.low)}–${money(x.high)} · USD/FEU · ${x.period}</small></article>`).join('');
 renderRoute(d);renderLog(d);$('newsGrid').innerHTML=d.news.map(n=>`<article><span>${n.date}</span><h3>${n.title}</h3><p>${n.source}</p></article>`).join('');
 $('sourceLinks').innerHTML=`<a href="https://api.vesselfinder.com/docs/" target="_blank">VesselFinder API</a><a href="https://portaktau.kz/en/infrastructure-2/" target="_blank">Aktau Port</a><a href="https://service.unece.org/trade/locode/kz.htm" target="_blank">UN/LOCODE</a>`;
}
function renderRoute(d){const m=d.mci,a=d.aktau;const svg=$('corridorSchematic');svg.innerHTML=`<defs><style>.r{fill:none;stroke:#111;stroke-width:5}.sea{fill:none;stroke:#477287;stroke-width:7;stroke-dasharray:13 8}.n{fill:#111}.t{font:700 22px Inter}.s{font:400 14px 'DM Mono'}.tag{fill:#d8ff39;stroke:#111}</style></defs><path class="r" d="M1130 430 L930 360 L790 345"/><path class="r" d="M790 345 L610 320"/><path class="sea" d="M610 320 C540 285 450 285 370 320"/><path class="r" d="M370 320 L265 285 L145 260"/><path class="r" d="M265 285 L165 420"/><circle class="n" cx="1130" cy="430" r="8"/><circle class="n" cx="930" cy="360" r="8"/><circle class="n" cx="790" cy="345" r="8"/><circle class="n" cx="610" cy="320" r="11"/><circle class="n" cx="370" cy="320" r="9"/><circle class="n" cx="265" cy="285" r="8"/><circle class="n" cx="145" cy="260" r="8"/><circle class="n" cx="165" cy="420" r="8"/><text class="t" x="1090" y="475">XI’AN</text><text class="t" x="885" y="405">KHORGOS</text><text class="t" x="735" y="305">ALTYNKOL</text><rect class="tag" x="555" y="350" width="110" height="38"/><text class="t" x="574" y="377">AKTAU</text><text class="s" x="545" y="410">${a.capacity_mt} Mt/y · ${a.berths} berths</text><text class="t" x="335" y="275">ALAT</text><text class="t" x="225" y="245">TBILISI</text><text class="t" x="88" y="220">ISTANBUL</text><text class="t" x="110" y="465">POTI / BLACK SEA</text><text class="s" x="455" y="255">CASPIAN SEA</text>`;
 $('rateLadder').innerHTML=d.mci.lanes.map(x=>`<div class="rate-row"><span>${x.code} · ${x.lane}</span><b>${money(x.midpoint)}</b><span>${money(x.low)}–${money(x.high)}</span></div>`).join('');$('routeStats').innerHTML=`<div><span>Aktau capacity</span><b>${a.capacity_mt} Mt/y</b></div><div><span>Aktau → Alat</span><b>${num(a.aktau_alat_teu)} TEU</b></div><div><span>Draft target</span><b>${a.draft_target}</b></div>`;set('officialTariffNote',`Aktau tariff-page reference carried by the monitor: ${a.tariff_date}. Through-rates above are not decomposed into invented port-by-port charges.`)}
function renderLog(d){const rows=[['2026-09-28','Aktau','Port capacity',`${d.aktau.capacity_mt} Mt/year`,'Aktau Port'],['2026-09-28','Aktau','AIS activity',d.ais.status==='live'?`${d.ais.vessels_in_area} vessels`:'awaiting API','VesselFinder'],['2026-09-24','Ocean','Shanghai–Rotterdam 40ft',money(d.ocean.shanghai_rotterdam_40ft),'Ocean benchmark'],['2026-09-09','Volume','Middle Corridor',num(d.corridor.teu_ytd)+' TEU','ADY Express']];const body=$('logRows');const paint=()=>{const q=$('searchBox').value.toLowerCase(),t=$('typeFilter').value;body.innerHTML=rows.filter(r=>(t==='all'||r[1]===t)&&r.join(' ').toLowerCase().includes(q)).map(r=>`<tr>${r.map((v,i)=>`<td>${v}</td>`).join('')}</tr>`).join('')};$('searchBox').oninput=paint;$('typeFilter').onchange=paint;paint()}
async function load(){try{const r=await fetch('data.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);render(await r.json())}catch(e){set('updateState','using last loaded snapshot')}}
function clock(){set('clockUtc','UTC '+new Date().toISOString().slice(11,19))}clock();setInterval(clock,1000);load();setInterval(load,300000);
